#!/usr/bin/env bash
# FlexPosit MICRO 2026 AE — Step 05: Figures 11 + 12 + Table 10 (hardware)
#
# The hardware artifact is self-contained under hardware/ — bundles:
#   - Analytical accelerator simulator (sim/)
#   - Ramulator 2.0 (prebuilt binary + rebuildable source)
#   - CACTI 22nm SRAM model
#   - Per-model layer-shape configs
#   - Pre-generated .log/CSV data + plot scripts
#
# Two reproduction levels:
#   DEFAULT: replots Figures 11 + 12 from shipped data (seconds), and runs the
#            bundled analytical simulator over 20 workload configs to regenerate
#            Table 10 from scratch and verify against expected/ (~2-3 h CPU).
#   FULL="1" mode: also regenerates Figure 11's 5 accelerator logs via the
#            simulator, then replots. Total ~2.5-3.5 h CPU.
#   Requires glibc >= 2.17 (Ubuntu 20.04+ / RHEL 8+); the CACTI + Ramulator
#   binaries are rebuilt from source by 01_install.sh with static libstdc++.
#
# Env flags:
#   FULL=1     Also regenerate Figure 11 data from simulator (adds ~30 min)
#   PY=/path   Python interpreter (default: current env's `python`)

set -euo pipefail

ENV_NAME="${ENV_NAME:-posit-ae}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HW_DIR="$REPO_ROOT/hardware"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$ENV_NAME"

PY="${PY:-python}"

echo "==========================================================="
echo "Figure 11 (hardware metrics) + Figure 12 (PPL vs EDP)"
echo "Hardware artifact: $HW_DIR"
echo "==========================================================="

# Ensure bundled binaries are executable (zip strips +x sometimes)
chmod +x "$HW_DIR/sim/mem/cacti/cacti" "$HW_DIR/ramulator/ramulator2" 2>/dev/null || true
# Simulator needs `python` on PATH; export the current conda env's python
export PATH="$(dirname "$(command -v "$PY")"):$PATH"

if [[ "${FULL:-0}" == "1" ]]; then
  echo "[FULL] Regenerating Figure 11 data via bundled simulator..."
  ( cd "$HW_DIR" && bash sim/run_fig11_sim.sh )
fi

echo "[sim] Regenerating Table 10 workload-sensitivity data (~2-3 h)..."
( cd "$HW_DIR" && bash sim/run_table7_sim.sh )

echo "[replot] Figure 11"
( cd "$HW_DIR" && "$PY" fig11_hardware_metrics/plot_fig11.py )

echo "[replot] Figure 12"
( cd "$HW_DIR" && "$PY" fig12_ppl_vs_edp/plot_fig12.py )

echo "[aggregate] Table 10"
( cd "$HW_DIR" && "$PY" table7_workload_sens/aggregate_table7.py )
mkdir -p "$REPO_ROOT/results"
cp "$HW_DIR/table7_workload_sens/table7_workload_sens.csv" \
   "$REPO_ROOT/results/table10_workload_sens.csv"

  # --- Cell-by-cell diff of Table 10 (24 cells) ---
  "$PY" - "$REPO_ROOT/results/table10_workload_sens.csv" \
         "$REPO_ROOT/expected/table10_workload_sens.csv" 0.1 <<'PY'
import csv, sys
prod_p, exp_p, tol = sys.argv[1], sys.argv[2], float(sys.argv[3])
def load(p):
    with open(p) as f:
        return {(r["batch_size"], r["context_length"]): r for r in csv.DictReader(f)}
prod, exp = load(prod_p), load(exp_p)
metrics = [c for c in next(iter(exp.values())) if c not in ("batch_size","context_length")]
print()
print("="*79)
print("[verify] Table 10 (batch/seqlen sensitivity)")
print("="*79)
print(f"  {'workload':>12s} {'metric':>28s} {'produced':>10s} {'expected':>10s} {'delta':>8s} status")
print("  " + "-"*72)
fails, worst = 0, 0.0
for k in sorted(prod):
    for m in metrics:
        if m not in exp[k]: continue
        p, e = float(prod[k][m]), float(exp[k][m])
        d = p - e
        if abs(d) > worst: worst = abs(d)
        status = "OK" if abs(d) <= tol else "FAIL"
        if status == "FAIL": fails += 1
        print(f"  ({k[0]:>2s},{k[1]:>4s})  {m:>28s} {p:>10.3f} {e:>10.3f} {d:>+8.3f} {status:>6s}")
n = len(prod) * len(metrics)
print("  " + "-"*72)
tag = "PASS" if fails == 0 else "FAIL"
print(f"  Result: {n-fails}/{n} cells within +/-{tol}  (max |Δ| = {worst:.3f})    {tag}")
print("="*79)
sys.exit(0 if fails == 0 else 1)
PY

echo
echo "==========================================================="
echo "Outputs (freshly regenerated by this run):"
echo "  Figure 11: $HW_DIR/fig11_hardware_metrics/fig11_hardware_metrics.{png,pdf}"
echo "  Figure 12: $HW_DIR/fig12_ppl_vs_edp/fig12_ppl_vs_edp.{png,pdf}"
echo "  Table 10:  $REPO_ROOT/results/table10_workload_sens.csv"
echo
echo "Reference (shipped for side-by-side visual comparison):"
echo "  Figure 11 ref: $HW_DIR/fig11_hardware_metrics/fig11_hardware_metrics_reference.{png,pdf}"
echo "  Figure 12 ref: $HW_DIR/fig12_ppl_vs_edp/fig12_ppl_vs_edp_reference.{png,pdf}"
echo
echo "Also compare CSVs against:"
echo "  expected/figure11_hardware.csv  (Norm.Latency / Norm.Energy / Norm.EDP / Norm.Energy-Eff.)"
echo "  expected/table10_workload_sens.csv  (Geomean speedup + energy reduction across 4 (B,L) workloads)"
echo "==========================================================="
